---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubelet-serving-approver
  namespace: kubelet-serving-approver
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet-serving-approver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubelet-serving-approver
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: kubelet-serving-approver
      containers:
      - name: approver
        image: ghcr.io/karelvanhecke/kubelet-serving-approver:v0.0.0
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 9080
        livenessProbe:
          tcpSocket:
            port: 9080
