---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubelet-serving-approver
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - update
- apiGroups:
  - certificates.k8s.io
  resources:
  - signers
  resourceNames:
  - kubernetes.io/kubelet-serving
  verbs:
  - approve
- apiGroups: [""]
  resources:
  - nodes
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubelet-serving-approver
subjects:
- kind: ServiceAccount
  name: kubelet-serving-approver
  namespace: kubelet-serving-approver
roleRef:
  kind: ClusterRole
  name: kubelet-serving-approver
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubelet-serving-approver
  namespace: kubelet-serving-approver
rules:
- apiGroups: [""]
  resources:
  - events
  verbs:
  - get
  - watch
  - list
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - watch
  - list
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubelet-serving-approver
  namespace: kubelet-serving-approver
subjects:
- kind: ServiceAccount
  name: kubelet-serving-approver
roleRef:
  kind: Role
  name: kubelet-serving-approver
  apiGroup: rbac.authorization.k8s.io
