kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kubelet-serving-approver
nodes:
- role: control-plane
  image: kindest/node:v1.33.4@sha256:25a6018e48dfcaee478f4a59af81157a437f15e6e140bf103f85a2e7cd0cbbf2
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        kubelet-certificate-authority: /etc/kubernetes/pki/ca.crt
  - |
    kind: KubeletConfiguration
    serverTLSBootstrap: true
