---
name: Check changes
on:
  workflow_call:
    outputs:
      go:
        description: Go code changed
        value: ${{ jobs.paths-filter.outputs.go }}
      deps:
        description: Dependencies changed
        value: ${{ jobs.paths-filter.outputs.deps }}

jobs:
  paths-filter:
    name: Paths filter
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.changes.outputs.go }}
      deps: ${{ steps.changes.outputs.deps }}
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Check changes
        id: changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            go:
              - '*.go'
              - 'go.mod'
              - 'go.sum'
              - '**/*.go'
            deps:
              - 'go.mod'
              - '.github/workflows/*'
