---
name: Check changes
on:
  workflow_call:
    outputs:
      go:
        description: Go code changed
        value: ${{ jobs.paths-filter.outputs.go }}
      deps:
        description: Dependencies changed
        value: ${{ jobs.paths-filter.outputs.deps }}
      container:
        description: Container changed
        value: ${{ jobs.paths-filter.outputs.container }}

jobs:
  paths-filter:
    name: Paths filter
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.changes.outputs.go }}
      deps: ${{ steps.changes.outputs.deps }}
      container: ${{ steps.changes.outputs.container }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check changes
        id: changes
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        with:
          filters: |
            container:
              - Dockerfile
            go:
              - '*.go'
              - 'go.mod'
              - 'go.sum'
              - '**/*.go'
            deps:
              - 'go.mod'
              - '.github/workflows/*'
