---
name: Continuous integration
on:
  pull_request:
    branches: ["main"]

jobs:
  check-changes:
    name: Check changes
    uses: ./.github/workflows/check-changes.yaml

  golangci-lint:
    name: Golangci-lint
    runs-on: ubuntu-latest
    needs: ["check-changes"]
    if: ${{ needs.check-changes.outputs.go == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 1.26.5

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.12.2

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: ["check-changes"]
    if: ${{ needs.check-changes.outputs.go == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 1.26.5

      - name: Run tests
        run: go test github.com/karelvanhecke/kubelet-serving-approver/...

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: ["check-changes"]
    if: ${{ needs.check-changes.outputs.go == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 1.26.5

      - name: Setup Kind
        env:
          KIND_VERSION: v0.30.0
        run: go install sigs.k8s.io/kind@${KIND_VERSION}

      - name: Setup kubectl
        env:
          KUBECTL_VERSION: v1.33.5
          KUBECTL_PATH: /usr/local/bin/kubectl
        run: |
          curl -s -L https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl | sudo tee $KUBECTL_PATH >/dev/null
          sha256sum $KUBECTL_PATH | grep -w $(curl -s -L https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl.sha256) >/dev/null
          sudo chmod +x $KUBECTL_PATH

      - name: Run integration tests
        run: tests/integration-tests.sh

  dependency-review:
    name: Dependency review
    runs-on: ubuntu-latest
    needs: ["check-changes"]
    if: ${{ needs.check-changes.outputs.deps == 'true' }}
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Review dependencies
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          comment-summary-in-pr: always
