name: Continuous integration
on:
  pull_request:
    branches: ["main"]

jobs:
  check-changes:
    name: Check changes
    uses: ./.github/workflows/check-changes.yaml

  golangci-lint:
    name: Golangci-lint
    runs-on: ubuntu-latest
    needs: ["check-changes"]
    if: ${{ needs.check-changes.outputs.go == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: 1.24.3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.1.6

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: ["check-changes"]
    if: ${{ needs.check-changes.outputs.go == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: 1.24.3

      - name: Run tests
        run: go test github.com/karelvanhecke/kubelet-serving-approver/...

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: ["check-changes"]
    if: ${{ needs.check-changes.outputs.go == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: 1.24.3

      - name: Setup Kind
        env:
          KIND_VERSION: v0.28.0
        run: go install sigs.k8s.io/kind@${KIND_VERSION}

      - name: Setup kubectl
        env:
          KUBECTL_VERSION: v1.32.5
          KUBECTL_PATH: /usr/local/bin/kubectl
        run: |
          curl -s -L https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl | sudo tee $KUBECTL_PATH >/dev/null
          sha256sum $KUBECTL_PATH | grep -w $(curl -s -L https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl.sha256) >/dev/null
          sudo chmod +x $KUBECTL_PATH

      - name: Run integration tests
        run: tests/integration-tests.sh

  dependency-review:
    name: Dependency review
    runs-on: ubuntu-latest
    needs: ["check-changes"]
    if: ${{ needs.check-changes.outputs.deps == 'true' }}
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Review dependencies
        uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9 # v4.7.1
        with:
          comment-summary-in-pr: always
