name: "Dependency review"

on:
  pull_request:
    branches: ["main"]

jobs:
  check-changes:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      deps: ${{ steps.changes.outputs.deps }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check changes
        id: changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            deps:
              - 'go.mod'
              - '.github/workflows/*'

  review:
    name: Review
    runs-on: ubuntu-latest
    needs: ["check-changes"]
    if: ${{ needs.check-changes.outputs.deps == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Review dependencies
        uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9 # v4.7.1
