---
name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.release-please.outputs.id }}
      release_created: ${{ steps.release-please.outputs.release_created }}
      sha: ${{ steps.release-please.outputs.sha }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
      version: ${{ steps.release-please.outputs.version }}
    steps:
      - name: Get app token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ vars.RELEASE_PLEASE_ID }}
          private-key: ${{ secrets.RELEASE_PLEASE_KEY }}

      - name: Run Release Please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release-please
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
          skip-github-pull-request: true

  container:
    name: Build and publish container
    needs: ["release-please"]
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    permissions:
      packages: write
      id-token: write
    env:
      IMAGE: ghcr.io/karelvanhecke/kubelet-serving-approver
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Setup cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
        with:
          cosign-release: v2.5.0

      - name: Login to GitHub registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        id: build
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          tags: ${{ env.IMAGE }}:v${{ needs.release-please.outputs.version }}
          provenance: false
          push: true

      - name: Sign container
        run: cosign sign --yes ${{ env.IMAGE }}@${{ steps.build.outputs.digest }}

  manifests:
    name: Generate and publish manifests
    runs-on: ubuntu-latest
    needs: ["release-please","container"]
    permissions:
      contents: write
      packages: write
      id-token: write
    env:
      MANIFEST: ghcr.io/karelvanhecke/manifests/kubelet-serving-approver
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup flux
        uses: fluxcd/flux2/action@1fd61a06264d71cf445ed55c4f14d401d26a1c64 # v2.8.8
        with:
          version: 2.7.2

      - name: Setup cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
        with:
          cosign-release: v3.0.2

      - name: Login to GitHub registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate manifests
        run: tools/release/generate_manifests.sh v${{ needs.release-please.outputs.version }}@${{ needs.container.outputs.digest }}

      - name: Upload manifest to release artifacts
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/octet-stream" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ needs.release-please.outputs.id }}/assets?name=kubelet-serving-approver.yaml" \
          --data-binary "@manifests/release.yaml"

      - name: Push manifest to OCI registry
        id: manifest
        run: |
          DIGEST=$(flux push artifact oci://${{ env.MANIFEST }}:v${{ needs.release-please.outputs.version }} \
          --path="./manifests/release.yaml" \
          --source="${{ github.repositoryUrl }}" \
          --revision="${{ needs.release-please.outputs.tag_name }}@sha1:${{ needs.release-please.outputs.sha }}" \
          -o json | jq -r .digest)
          echo "digest=${DIGEST}" >> "$GITHUB_OUTPUT"

      - name: Sign manifest
        run: cosign sign --yes ${{ env.MANIFEST }}@${{ steps.manifest.outputs.digest }}

  publish:
    name: Publish release
    runs-on: ubuntu-latest
    needs: ["release-please","container","manifests"]
    permissions:
      contents: write
    steps:
      - name: Publish release
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          ${{ github.api_url }}/repos/${{ github.repository }}/releases/${{ needs.release-please.outputs.id }} \
          -d '{"draft": false}'

  release-please-pr:
    name: Release Please PR
    runs-on: ubuntu-latest
    needs: ["release-please","container","manifests","publish"]
    if: ${{ !cancelled() && !failure() }}
    steps:
      - name: Get app token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ vars.RELEASE_PLEASE_ID }}
          private-key: ${{ secrets.RELEASE_PLEASE_KEY }}

      - name: Run Release Please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release-please
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
          skip-github-release: true
